record_type: FD0
record_name: Service Line Detail Dental Segment
record_length: 320
order: 18
preceding_rules: []
following_rules: []
record_rules:
- This record is not used for commercial claims.
fields: []
