record_type: GC0
record_name: Chiropractic Certification Record
record_length: 320
order: 21
preceding_rules: []
following_rules: []
record_rules:
- This record is not used for commercial claims.
fields: []
