record_type: GX0
record_name: Oxygen Certification Record --
record_length: 320
order: 27
preceding_rules: []
following_rules: []
record_rules:
- Medical Necessity for Oxygen
- This record is not used for commercial claims.
fields: []
