record_type: '01'
record_name: Processor Data 6
record_length: 192
order: 0
preceding_rules: []
following_rules:
- ▪ Must be followed by Record Type 10
record_rules:
- UB-92
- File
- Specifications
- Version 510
- 'Implementation Date: August 14, 2011'
- 'Revision Date: February 2012'
- Table of Contents
- Introduction 4
- ▪ Only one 01 record is allowed per file; Must be the first record on the
- file.
- Field Positions Req
- No. From To Picture Field Field Name/Description
- Field Positions Req
- No. From To Picture Field Field Name/Description
fields:
- field_number: '01'
  start_position: 1
  end_position: 2
  cobol_picture: X(2)
  requirement_code: R
  field_name: Record Type - Must be ‘01’
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 197
  calculated_length: 2
  canonical_name: record_type_must_be_01
- field_number: '02'
  start_position: 3
  end_position: 12
  cobol_picture: 9(10)
  requirement_code: R
  field_name: Submitter EIN
  description: The Employer Identification Number (EIN) of the submitter preceded
    by a zero (0). First position must be equal to ‘0’.
  allowed_values:
  - position must be equal to ‘0’.
  conditional_rules: []
  formatting_notes: []
  source_line: 199
  calculated_length: 10
  canonical_name: submitter_ein
- field_number: '03'
  start_position: 13
  end_position: 13
  cobol_picture: 9(1)
  requirement_code: N
  field_name: Multiple Provider Billing File Indicator
  description: Used to indicate the occurrence of multiple providers within the file.
    1 = Single Provider 2 = Multiple Providers
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 204
  calculated_length: 1
  canonical_name: multiple_provider_billing_file_indicator
- field_number: '04'
  start_position: 14
  end_position: 30
  cobol_picture: X(17)
  requirement_code: N
  field_name: Filler (National Use) - Unused record space
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 210
  calculated_length: 17
  canonical_name: filler_national_use_unused_record_space
- field_number: '05'
  start_position: 31
  end_position: 31
  cobol_picture: X(1)
  requirement_code: R
  field_name: Receiver Type Code
  description: Indicates the organization designated to receive this file. F = Insurance
    Company. Must be entered.
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 212
  calculated_length: 1
  canonical_name: receiver_type_code
- field_number: '06'
  start_position: 32
  end_position: 36
  cobol_picture: 9(5)
  requirement_code: R
  field_name: Receiver Identification
  description: A number used to identify the organization to receive the file. UnitedHealthcare
    = 87726
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 217
  calculated_length: 5
  canonical_name: receiver_identification
- field_number: '07'
  start_position: 37
  end_position: 40
  cobol_picture: X(4)
  requirement_code: N
  field_name: Receiver Sub-Identification
  description: A number used to identify the specific location within the receiver’s
    organization to receive the file.
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 221
  calculated_length: 4
  canonical_name: receiver_sub_identification
- field_number: 08
  start_position: 41
  end_position: 46
  cobol_picture: X(6)
  requirement_code: N
  field_name: Filler (National Use) - Unused record space
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 226
  calculated_length: 6
  canonical_name: filler_national_use_unused_record_space
- field_number: 09
  start_position: 47
  end_position: 67
  cobol_picture: X(21)
  requirement_code: O
  field_name: Submitter Name
  description: 'The name of the organization submitting the claim file. Submitter
    Address (Fields 10 - 13) - Address of the submitting organization. See Exhibit
    # 2 Standard Address Checks'
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 228
  calculated_length: 21
  canonical_name: submitter_name
- field_number: '10'
  start_position: 68
  end_position: 85
  cobol_picture: X(18)
  requirement_code: O
  field_name: Submitter Address
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 236
  calculated_length: 18
  canonical_name: submitter_address
- field_number: '11'
  start_position: 86
  end_position: 100
  cobol_picture: X(15)
  requirement_code: O
  field_name: Submitter City
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 238
  calculated_length: 15
  canonical_name: submitter_city
- field_number: '12'
  start_position: 101
  end_position: 102
  cobol_picture: X(2)
  requirement_code: O
  field_name: Submitter State
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 240
  calculated_length: 2
  canonical_name: submitter_state
- field_number: '13'
  start_position: 103
  end_position: 111
  cobol_picture: X(9)
  requirement_code: O
  field_name: Submitter Zip Code
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 242
  calculated_length: 9
  canonical_name: submitter_zip_code
- field_number: '14'
  start_position: 112
  end_position: 121
  cobol_picture: 9(10)
  requirement_code: N
  field_name: Submitter Fax Number - Not used
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 244
  calculated_length: 10
  canonical_name: submitter_fax_number_not_used
- field_number: '15'
  start_position: 122
  end_position: 125
  cobol_picture: X(4)
  requirement_code: N
  field_name: Submitter Country Code - Not used
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 246
  calculated_length: 4
  canonical_name: submitter_country_code_not_used
- field_number: '16'
  start_position: 126
  end_position: 135
  cobol_picture: 9(10)
  requirement_code: O
  field_name: Submitter Telephone Number
  description: Telephone number of the submitter. Format = XXXYYYZZZZ XXX = Area Code
    YYY = Exchange ZZZZ = Station Number
  allowed_values: []
  conditional_rules: []
  formatting_notes:
  - Telephone number of the submitter. Format =
  source_line: 248
  calculated_length: 10
  canonical_name: submitter_telephone_number
- field_number: '17'
  start_position: 136
  end_position: 142
  cobol_picture: X(7)
  requirement_code: R
  field_name: File Sequence & Serial Number
  description: The number assigned by the submitter for the claim file. Must be unique
    for every new file submitted.
  allowed_values:
  - claim file. Must be unique for every new file
  conditional_rules: []
  formatting_notes: []
  source_line: 254
  calculated_length: 7
  canonical_name: file_sequence_serial_number
- field_number: '18'
  start_position: 143
  end_position: 146
  cobol_picture: X(4)
  requirement_code: R
  field_name: Test/Production Indicator
  description: 'Indicates if the file is for adjudication or testing purposes. Code
    Values: PROD = Production TEST = Test'
  allowed_values: []
  conditional_rules:
  - Indicates if the file is for adjudication or
  formatting_notes: []
  source_line: 259
  calculated_length: 4
  canonical_name: test_production_indicator
- field_number: '19'
  start_position: 147
  end_position: 154
  cobol_picture: 9(8)
  requirement_code: N
  field_name: Date of Receipt
  description: The date the file was received from the submitter. This is to be entered
    by the receiver of the file. Format = CCYYMMDD
  allowed_values: []
  conditional_rules: []
  formatting_notes:
  - The date the file was received from the
  - receiver of the file. Format = CCYYMMDD
  source_line: 271
  calculated_length: 8
  canonical_name: date_of_receipt
- field_number: '20'
  start_position: 155
  end_position: 162
  cobol_picture: 9(8)
  requirement_code: R
  field_name: Processing Date
  description: The date the submitter prepares the file for transmission to the receiver.
    Format = CCYYMMDD
  allowed_values: []
  conditional_rules: []
  formatting_notes:
  - The date the submitter prepares the file for
  - transmission to the receiver. Format = CCYYMMDD
  source_line: 276
  calculated_length: 8
  canonical_name: processing_date
- field_number: '21'
  start_position: 163
  end_position: 189
  cobol_picture: X(27)
  requirement_code: N
  field_name: Filler (Local Use) - Unused record space
  description: ''
  allowed_values: []
  conditional_rules: []
  formatting_notes: []
  source_line: 280
  calculated_length: 27
  canonical_name: filler_local_use_unused_record_space
- field_number: '22'
  start_position: 190
  end_position: 192
  cobol_picture: X(3)
  requirement_code: R
  field_name: Version Code
  description: A code used to identify the version of the specification format being
    used. Must be equal to ‘510’.
  allowed_values:
  - specification format being used. Must be equal
  conditional_rules: []
  formatting_notes:
  - specification format being used. Must be equal
  source_line: 282
  calculated_length: 3
  canonical_name: version_code
