record_type: '74'
record_name: Currently not used. 40
record_length: 192
order: 20
preceding_rules: []
following_rules: []
record_rules:
- Health Data Elements for Medical Review of Home
- Health Claims - Patient Information
- ▪ Record Type 74 currently not used. If submitted, will not be
- processed.
- Field Positions Req
- No. From To Picture Field Field
- Name/Description
fields: []
