{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "human-review-api.serviceAccountName" . }}
  labels:
    {{- include "human-review-api.labels" . | nindent 4 }}
{{- end }}
